spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ssmbuild?rewriteBatchedStatements=true&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: 1375632510
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ssm?rewriteBatchedStatements=true&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: 1375632510
  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印执行的sql


